Features/sloths 30 implement request payload validation
ItsCuriousChimp/team_sloths pull request #23
Opened 2022-07-25 10:37 UTC by jitender-chaudhary

request-payload-validation

2022-07-25 10:43 UTC, kartikbb requested changes

2022-08-01 12:04 UTC, kartikbb requested changes

2022-08-02 12:02 UTC, vrknetha requested changes

2022-08-02 12:02 UTC, vrknetha commented on .env
> +DATABASE_URL="postgresql://postgres:j1C@jitua@localhost:5432/bookMyShow?schema=public"
do not commit the .env file, add it to gitignore

2022-08-02 12:02 UTC, vrknetha commented on src/controllers/base.controller.ts
> +  public extractAndValidate(src: any, Dest: any) {
do not use the type as any. create an interface with data type and mention it.

2022-08-02 12:02 UTC, vrknetha commented on tsconfig.json
> +    "experimentalDecorators": true,
experimentalDecorators declared twice

2022-08-02 12:03 UTC, vrknetha requested changes

2022-08-02 12:03 UTC, vrknetha commented on .env
> +DATABASE_URL="postgresql://postgres:j1C@jitua@localhost:5432/bookMyShow?schema=public"
do not commit the .env file , add it to git ignore

2022-08-02 14:32 UTC, kartikbb approved these changes

2022-08-02 15:38 UTC, jitender-chaudhary commented on src/controllers/base.controller.ts
> +  public extractAndValidate(src: any, Dest: any) {
BaseController has been created as generic class and  extractAndValidate take Dest of different types, it could be from andy three request payload that's why gave it to generic type.

2022-08-03 10:49 UTC, closed without merging